name: Build and upload tally

on: 
  push: 
    branches:
      - main

jobs:
  build-linux : 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Build project
      run: go build -o tally

    - name: Upload release binary
      uses: actions/upload-artifact@v4
      with:
        name: tally
        path: tally

  build-windows : 
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Build project
      run: go build -o tally.exe

    - name: Upload release binary
      uses: actions/upload-artifact@v4
      with:
        name: tally.exe
        path: tally.exe